import { useUIStore } from '@/stores/useUIStore'

export type Locale = 'en' | 'vi'

const en = {
  appName: 'What Should I Eat?', home: 'Home', findFood: 'Find Food', random: 'Random', favorites: 'Favorites',
  mainNavigation: 'Main navigation', language: 'Language', madeWith: 'Made with', forHungryStudents: 'for hungry students',
  viewDetails: 'View Details', match: 'Match', minute: 'min', save: 'Save', saved: 'Saved', addFavorite: 'Add to favorites', removeFavorite: 'Remove from favorites',
  restaurant: 'Restaurant', address: 'Address', openMap: 'Open in Maps',
  heroBadge: 'Your next favorite meal is close', heroTitleBefore: 'What should', heroTitleAccent: 'I eat?', heroDescription: "Not sure what to eat today? Tell us what you're looking for and we'll help you decide.",
  findMyFood: 'Find My Food', surpriseMe: 'Surprise Me', diversePicks: '56 diverse picks', smartMatching: 'Smart matching', noSignup: 'No sign-up', heroAlt: 'A colorful Vietnamese food spread', todaysMood: "Today's mood", moodText: 'Warm, savory & satisfying',
  simpleByDesign: 'Simple by design', threeSteps: 'Dinner decided in three steps', step1Title: 'Choose your preferences', step1Text: 'Tell us your budget, time, tastes, and who is joining.', step2Title: 'We find the best matches', step2Text: 'A transparent score compares each dish—nothing is random.', step3Title: 'Pick something delicious', step3Text: 'See exactly why each meal fits, then save your favorites.',
  tasteInside: "A taste of what's inside", popularNow: 'Popular right now', findYourMatch: 'Find your match',
  makeItYours: 'Make it yours', preferenceTitle: 'What are you in the mood for?', preferenceIntro: "Pick only what matters today. Anything left open won't lower your match scores.", step: 'Step',
  budgetTitle: "What's your budget?", budgetHint: 'We score nearby prices gently—not with a hard cut-off.', timeTitle: 'How much time do you have?', timeHint: "Pick the longest you're happy to wait.", flavorTitle: 'What flavors sound good?', flavorHint: 'Choose as many as you like.', categoryTitle: 'Pick a category', categoryHint: 'Or leave it open for a wider mix.', companyTitle: 'Who are you eating with?', companyHint: 'Some meals are simply better shared.', dietaryTitle: 'Any dietary restrictions?', dietaryHint: 'These are strict filters, so every result will respect them.',
  under30: 'Under 30,000đ', budgetQuick: 'Quick & budget-friendly', budget30to50: '30,000 – 50,000đ', budgetEveryday: 'Everyday favorites', budget50to100: '50,000 – 100,000đ', budgetSpecial: 'A little more special', over100: 'Over 100,000đ', budgetTreat: 'Treat yourself', noPreference: 'No preference', showEverything: 'Show me everything', under15: 'Under 15 min', time15to30: '15 – 30 min', time30to60: '30 – 60 min', vegetarian: 'Vegetarian', noBeef: 'No Beef', noPork: 'No Pork', noSeafood: 'No Seafood',
  personalized: 'Personalized for you', bestMatches: 'Best matches for you', matchIntro: 'Every score is calculated from your active choices. Dietary restrictions are always applied first.', changePreferences: 'Change Preferences', tellUs: 'Tell us what sounds good', tellUsDescription: "Choose a few preferences first, and we'll calculate your best matches.", setPreferences: 'Set my preferences', noRestrictionMatches: 'No dishes match every restriction', noRestrictionDescription: 'Try adjusting one of your dietary filters to open up more choices.', adjustPreferences: 'Adjust preferences', dishesMatch: 'dishes match your dietary needs', sortedByScore: 'Sorted by match score',
  savedForLater: 'Saved for later', yourFavorites: 'Your favorites', savedDescription: 'Your saved dishes stay here—even after you refresh.', nothingSaved: 'Nothing saved yet', nothingSavedDescription: 'Tap the heart on any dish you love and it will appear here.', findSomething: 'Find something delicious',
  cantDecide: "Can't decide?", fateIntro: 'Let fate choose your next meal.', usePreferences: 'Use my preferences', above60: 'Only spin through matches above 60%', noPreferences: "No preferences saved yet, so we'll use every dish.", setPreferencesShort: 'Set preferences', fateChose: 'Fate chose', mealAwaits: 'Your meal awaits', oneTap: 'One tap is all it takes. We promise not to judge the result.', noMatches60: 'No matches above 60%', adjustOrDisable: 'Adjust your preferences or turn off the preference filter.', choosing: 'CHOOSING...', spinAgain: 'SPIN AGAIN', spin: 'SPIN', choosingFrom: 'Choosing from', deliciousOptions: 'delicious options',
  dishMissing: "We couldn't find that dish", dishMissingDescription: "It may have been removed from today's menu.", backHome: 'Back home', backMatches: 'Back to matches', price: 'Price', readyIn: 'Ready in', bestWith: 'Best with', ingredients: 'Ingredients', dietaryInfo: 'Dietary information', containsMeat: 'Contains meat', containsBeef: 'Contains beef', containsPork: 'Contains pork', containsSeafood: 'Contains seafood', noBeefFact: 'No beef', noPorkFact: 'No pork', noSeafoodFact: 'No seafood', whyRecommend: 'Why we recommend this', setForScore: 'Set your preferences to see a personal match score and clear reasons.', setPreferencesArrow: 'Set preferences →', goodCompany: 'Good company:',
  notFoundTitle: 'This table is empty', notFoundDescription: "The page you were looking for isn't on today's menu.",
} as const

const vi: Record<keyof typeof en, string> = {
  appName: 'Hôm nay ăn gì?', home: 'Trang chủ', findFood: 'Tìm món', random: 'Ngẫu nhiên', favorites: 'Yêu thích',
  mainNavigation: 'Điều hướng chính', language: 'Ngôn ngữ', madeWith: 'Được làm với', forHungryStudents: 'cho những chiếc bụng đói',
  viewDetails: 'Xem chi tiết', match: 'Phù hợp', minute: 'phút', save: 'Lưu', saved: 'Đã lưu', addFavorite: 'Thêm vào yêu thích', removeFavorite: 'Bỏ khỏi yêu thích',
  restaurant: 'Quán ăn', address: 'Địa chỉ', openMap: 'Mở bản đồ',
  heroBadge: 'Món yêu thích tiếp theo đang ở rất gần', heroTitleBefore: 'Hôm nay', heroTitleAccent: 'ăn gì?', heroDescription: 'Chưa biết hôm nay ăn gì? Hãy cho chúng mình biết mong muốn của bạn để tìm ra lựa chọn phù hợp.',
  findMyFood: 'Tìm món cho tôi', surpriseMe: 'Chọn bất ngờ', diversePicks: '56 lựa chọn đa dạng', smartMatching: 'Gợi ý thông minh', noSignup: 'Không cần đăng ký', heroAlt: 'Bàn đồ ăn Việt Nam đầy màu sắc', todaysMood: 'Tâm trạng hôm nay', moodText: 'Ấm nóng, đậm đà và thật thỏa mãn',
  simpleByDesign: 'Đơn giản và dễ dùng', threeSteps: 'Chọn món ngon chỉ trong ba bước', step1Title: 'Chọn sở thích', step1Text: 'Cho chúng mình biết ngân sách, thời gian, khẩu vị và người ăn cùng.', step2Title: 'Tìm lựa chọn phù hợp nhất', step2Text: 'Điểm số minh bạch giúp so sánh từng món theo mong muốn của bạn.', step3Title: 'Chọn một món thật ngon', step3Text: 'Xem lý do món ăn phù hợp rồi lưu lại những món bạn yêu thích.',
  tasteInside: 'Một chút hương vị trong ứng dụng', popularNow: 'Đang được yêu thích', findYourMatch: 'Tìm món hợp gu',
  makeItYours: 'Chọn theo ý bạn', preferenceTitle: 'Hôm nay bạn muốn ăn gì?', preferenceIntro: 'Chỉ chọn những điều quan trọng với bạn hôm nay. Mục để trống sẽ không làm giảm điểm phù hợp.', step: 'Bước',
  budgetTitle: 'Ngân sách của bạn là bao nhiêu?', budgetHint: 'Mức giá gần ngân sách vẫn được tính điểm linh hoạt.', timeTitle: 'Bạn có bao nhiêu thời gian?', timeHint: 'Chọn thời gian lâu nhất bạn sẵn sàng chờ.', flavorTitle: 'Bạn thích hương vị nào?', flavorHint: 'Có thể chọn nhiều khẩu vị.', categoryTitle: 'Chọn loại món', categoryHint: 'Hoặc để mở để có nhiều lựa chọn hơn.', companyTitle: 'Bạn ăn cùng ai?', companyHint: 'Có những món sẽ ngon hơn khi được sẻ chia.', dietaryTitle: 'Bạn có kiêng món gì không?', dietaryHint: 'Đây là bộ lọc bắt buộc; mọi kết quả đều sẽ tuân thủ.',
  under30: 'Dưới 30.000đ', budgetQuick: 'Nhanh và tiết kiệm', budget30to50: '30.000 – 50.000đ', budgetEveryday: 'Món ngon hằng ngày', budget50to100: '50.000 – 100.000đ', budgetSpecial: 'Đặc biệt hơn một chút', over100: 'Trên 100.000đ', budgetTreat: 'Tự thưởng cho mình', noPreference: 'Không yêu cầu', showEverything: 'Hiển thị tất cả', under15: 'Dưới 15 phút', time15to30: '15 – 30 phút', time30to60: '30 – 60 phút', vegetarian: 'Ăn chay', noBeef: 'Không thịt bò', noPork: 'Không thịt heo', noSeafood: 'Không hải sản',
  personalized: 'Dành riêng cho bạn', bestMatches: 'Những món hợp với bạn nhất', matchIntro: 'Điểm số được tính từ các lựa chọn đang áp dụng. Yêu cầu ăn kiêng luôn được ưu tiên trước.', changePreferences: 'Đổi sở thích', tellUs: 'Hãy cho chúng mình biết bạn muốn ăn gì', tellUsDescription: 'Chọn một vài sở thích trước, rồi chúng mình sẽ tính những món phù hợp nhất.', setPreferences: 'Thiết lập sở thích', noRestrictionMatches: 'Không có món đáp ứng mọi yêu cầu', noRestrictionDescription: 'Hãy điều chỉnh một bộ lọc ăn kiêng để có thêm lựa chọn.', adjustPreferences: 'Điều chỉnh sở thích', dishesMatch: 'món phù hợp với chế độ ăn của bạn', sortedByScore: 'Xếp theo độ phù hợp',
  savedForLater: 'Đã lưu để xem sau', yourFavorites: 'Món yêu thích', savedDescription: 'Các món đã lưu vẫn ở đây kể cả sau khi bạn tải lại trang.', nothingSaved: 'Chưa có món nào được lưu', nothingSavedDescription: 'Nhấn biểu tượng trái tim trên món bạn thích để lưu vào đây.', findSomething: 'Tìm một món thật ngon',
  cantDecide: 'Chưa biết chọn gì?', fateIntro: 'Hãy để vận may chọn bữa tiếp theo cho bạn.', usePreferences: 'Dùng sở thích của tôi', above60: 'Chỉ chọn các món phù hợp từ 60% trở lên', noPreferences: 'Bạn chưa lưu sở thích nên chúng mình sẽ chọn trong tất cả món.', setPreferencesShort: 'Thiết lập sở thích', fateChose: 'Vận may đã chọn', mealAwaits: 'Món ngon đang chờ bạn', oneTap: 'Chỉ cần một lần nhấn. Kết quả nào cũng đáng để thử!', noMatches60: 'Không có món phù hợp trên 60%', adjustOrDisable: 'Hãy đổi sở thích hoặc tắt bộ lọc sở thích.', choosing: 'ĐANG CHỌN...', spinAgain: 'CHỌN LẠI', spin: 'CHỌN MÓN', choosingFrom: 'Đang chọn trong', deliciousOptions: 'món ngon',
  dishMissing: 'Không tìm thấy món ăn', dishMissingDescription: 'Món này có thể đã được gỡ khỏi thực đơn hôm nay.', backHome: 'Về trang chủ', backMatches: 'Quay lại kết quả', price: 'Giá', readyIn: 'Thời gian', bestWith: 'Ăn cùng', ingredients: 'Nguyên liệu', dietaryInfo: 'Thông tin ăn kiêng', containsMeat: 'Có thịt', containsBeef: 'Có thịt bò', containsPork: 'Có thịt heo', containsSeafood: 'Có hải sản', noBeefFact: 'Không thịt bò', noPorkFact: 'Không thịt heo', noSeafoodFact: 'Không hải sản', whyRecommend: 'Vì sao món này phù hợp', setForScore: 'Thiết lập sở thích để xem điểm phù hợp và lý do gợi ý.', setPreferencesArrow: 'Thiết lập sở thích →', goodCompany: 'Phù hợp khi ăn:',
  notFoundTitle: 'Bàn này đang trống', notFoundDescription: 'Trang bạn tìm không có trong thực đơn hôm nay.',
}

export const messages = { en, vi }

export function useI18n() {
  const locale = useUIStore((state) => state.locale)
  const setLocale = useUIStore((state) => state.setLocale)
  return { locale, setLocale, t: messages[locale] }
}
