import { createFileRoute, Link } from '@tanstack/react-router'
import { ArrowLeft, Check, Clock3, Leaf, ShieldCheck, Soup, Users } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { FavoriteButton } from '@/features/food/components/FavoriteButton'
import { FoodImage } from '@/features/food/components/FoodImage'
import { getFoodById } from '@/features/food/data/foods'
import { categoryLabels, eatingContextLabels, formatVnd, tasteLabels } from '@/features/food/food.utils'
import { scoreFood } from '@/features/recommendation/recommendation'
import { useFoodStore } from '@/stores/useFoodStore'

export const Route = createFileRoute('/foods/$foodId')({ component: FoodDetailPage })
function FoodDetailPage() {
  const { foodId } = Route.useParams()
  const preferences = useFoodStore((state) => state.preferences)
  const food = getFoodById(foodId)
  if (!food) return <div className="mx-auto max-w-3xl px-4 py-24 text-center"><span className="mx-auto grid size-16 place-items-center rounded-2xl bg-orange-50 text-orange-500"><Soup className="size-7" /></span><h1 className="font-display mt-5 text-4xl font-bold">We couldn't find that dish</h1><p className="mt-3 text-stone-500">It may have been removed from today's menu.</p><Button asChild className="mt-7 rounded-full bg-stone-900"><Link to="/">Back to home</Link></Button></div>
  const recommendation = preferences ? scoreFood(food, preferences) : null
  const dietaryFacts = [food.dietary.vegetarian ? 'Vegetarian' : 'Contains meat', food.dietary.containsBeef ? 'Contains beef' : 'No beef', food.dietary.containsPork ? 'Contains pork' : 'No pork', food.dietary.containsSeafood ? 'Contains seafood' : 'No seafood']
  return <div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
    <Link to={preferences ? '/recommendations' : '/'} className="mb-7 inline-flex items-center gap-2 text-sm font-semibold text-stone-500 hover:text-orange-600"><ArrowLeft className="size-4" /> {preferences ? 'Back to matches' : 'Back home'}</Link>
    <div className="grid gap-10 lg:grid-cols-[1.08fr_.92fr] lg:items-start"><FoodImage src={food.image} alt={food.name} className="h-[360px] rounded-[2rem] shadow-xl shadow-stone-200 sm:h-[520px]" /><div className="lg:py-3"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-orange-100 px-3 py-1.5 text-xs font-bold tracking-wide text-orange-700 uppercase">{categoryLabels[food.category]}</span>{food.tags.map((tag) => <span key={tag} className="rounded-full bg-stone-100 px-3 py-1.5 text-xs font-semibold text-stone-600">{tag}</span>)}</div><h1 className="font-display mt-5 text-4xl font-bold tracking-tight sm:text-6xl">{food.name}</h1><p className="mt-4 text-lg leading-8 text-stone-500">{food.description}</p><div className="my-7 grid grid-cols-3 divide-x divide-stone-200 rounded-2xl border border-stone-200 bg-white py-4 text-center shadow-sm"><div><p className="text-xs text-stone-400">Price</p><p className="mt-1 font-bold">{formatVnd(food.price)}</p></div><div><p className="text-xs text-stone-400">Ready in</p><p className="mt-1 flex items-center justify-center gap-1 font-bold"><Clock3 className="size-4 text-orange-500" /> {food.preparationTime} min</p></div><div><p className="text-xs text-stone-400">Best with</p><p className="mt-1 flex items-center justify-center gap-1 font-bold capitalize"><Users className="size-4 text-orange-500" /> {food.suitableFor[0]}</p></div></div><div className="flex flex-wrap gap-2">{food.tastes.map((taste) => <span key={taste} className="rounded-full border border-orange-200 bg-orange-50 px-3 py-1.5 text-sm font-semibold text-orange-700">{tasteLabels[taste]}</span>)}</div><div className="mt-7"><FavoriteButton foodId={food.id} showLabel className="h-12 px-6" /></div></div></div>
    <div className="mt-14 grid gap-6 lg:grid-cols-3"><section className="rounded-[1.5rem] border border-stone-200 bg-white p-6"><h2 className="font-display flex items-center gap-2 text-xl font-bold"><Soup className="size-5 text-orange-500" /> Ingredients</h2><ul className="mt-5 grid gap-3">{food.ingredients.map((ingredient) => <li key={ingredient} className="flex items-center gap-2 text-sm text-stone-600"><span className="size-1.5 rounded-full bg-orange-400" />{ingredient}</li>)}</ul></section><section className="rounded-[1.5rem] border border-stone-200 bg-white p-6"><h2 className="font-display flex items-center gap-2 text-xl font-bold"><ShieldCheck className="size-5 text-emerald-500" /> Dietary information</h2><ul className="mt-5 grid gap-3">{dietaryFacts.map((fact, index) => <li key={fact} className="flex items-center gap-2 text-sm text-stone-600">{index === 0 && food.dietary.vegetarian ? <Leaf className="size-4 text-emerald-500" /> : <Check className="size-4 text-emerald-500" />}{fact}</li>)}</ul></section><section className="rounded-[1.5rem] border border-orange-200 bg-orange-50 p-6"><h2 className="font-display flex items-center justify-between gap-3 text-xl font-bold"><span>Why we recommend this</span>{recommendation ? <span className="shrink-0 rounded-full bg-stone-900 px-3 py-1.5 text-sm text-white"><strong className="text-orange-300">{recommendation.score}%</strong> Match</span> : null}</h2>{recommendation ? <ul className="mt-5 grid gap-3">{recommendation.reasons.map((reason) => <li key={reason} className="flex items-start gap-2 text-sm text-stone-700"><span className="mt-0.5 grid size-4 shrink-0 place-items-center rounded-full bg-emerald-500 text-white"><Check className="size-2.5" /></span>{reason}</li>)}</ul> : <div className="mt-5"><p className="text-sm leading-6 text-stone-600">Set your preferences to see a personal match score and clear reasons.</p><Link to="/preferences" className="mt-3 inline-block text-sm font-bold text-orange-700">Set preferences →</Link></div>}</section></div>
    <div className="mt-8 rounded-2xl bg-stone-100 px-5 py-4 text-sm text-stone-500"><strong className="text-stone-700">Good company:</strong> {food.suitableFor.map((item) => eatingContextLabels[item].toLowerCase()).join(', ')}.</div>
  </div>
}
